cookbook/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^ingredients/$', views.IngredientsView.as_view(), name='ingredients'),
    url(r'^ingredient/create$', views.IngredientCreate.as_view(),
        name='create_ingredient'),
    url(r'^ingredient/(?P<pk>[0-9]+)/edit$', views.IngredientUpdate.as_view(),
        name='edit_ingredient'),
    url(r'^ingredient/(?P<pk>[0-9]+)/delete$', views.IngredientDelete.as_view(),
        name='delete_ingredient'),
    url(r'^measurements/$', views.MeasurementView.as_view(),
        name='measurements'),
    url(r'^measurement/create$', views.MeasurementCreate.as_view(),
        name="create_measurement"),
    url(r'^measurement/(?P<pk>[0-9]+)/edit$', views.MeasurementEdit.as_view(),
        name='edit_measurement'),
    url(r'^measurement/(?P<pk>[0-9]+)/delete$',
        views.MeasurementDelete.as_view(),
        name='delete_measurement'),
]

kube_cd_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^cookbook/', include('cookbook.urls', namespace="cookbook")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$',
        views.ResultsView.as_view(),
        name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

cookbook/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Meal(models.Model):

    name = models.CharField(max_length=500)
    stub = models.CharField(max_length=500)
    instructions = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):

    name = models.CharField(max_length=500)
    stub = models.CharField(max_length=500)
    description = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('cookbook:edit_ingredient', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Measurement(models.Model):
    name = models.CharField(max_length=500)
    stub = models.CharField(max_length=500)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cookbook:edit_measurement', kwargs={'pk': self.pk})


class Recipe(models.Model):
    meal = models.ForeignKey(Meal)
    ingredient = models.ForeignKey(Ingredient)
    quantity = models.FloatField()
    measurement = models.ForeignKey(Measurement)

cookbook/forms.py
from django import forms
from .models import (
    # Recipe,
    Ingredient,
    # Measurement,
    # Meal
)


class IngredientForm(forms.ModelForm):

    """Manage ingredients."""

    class Meta:
        model = Ingredient
        fields = ['name', 'stub', 'description']

cookbook/views.py
from django.views import generic
from django.conf import settings
from django.core.urlresolvers import reverse_lazy

from .models import Meal, Ingredient, Measurement


class IndexView(generic.ListView):

    template_name = 'cookbook/index.html'
    context_object_name = 'meal_list'

    def get_context_data(self, **kwargs):
        """Return the context data

        :**kwargs: arguments
        :returns: context object for view

        """
        context = super(IndexView, self).get_context_data(**kwargs)
        context['version'] = settings.VERSION
        return context

    def get_queryset(self):
        return Meal.objects.all()


class IngredientsView(generic.ListView):
    template_name = 'cookbook/ingredients.html'

    def get_context_data(self, **kwargs):
        """Return the context data

        :**kwargs: arguments
        :returns: context object for view

        """
        context = super(IngredientsView, self).get_context_data(**kwargs)
        context['version'] = settings.VERSION
        return context

    def get_queryset(self):
        return Ingredient.objects.all()


class IngredientCreate(generic.edit.CreateView):
    model = Ingredient
    fields = ['name', 'stub', 'description']
    success_url = reverse_lazy('cookbook:ingredients')

    def get_context_data(self, **kwargs):
        """Return the context data

        :**kwargs: arguments
        :returns: context object for view

        """
        context = super(IngredientCreate, self).get_context_data(**kwargs)
        context['version'] = settings.VERSION
        return context


class IngredientUpdate(generic.edit.UpdateView):
    model = Ingredient
    fields = ['name', 'stub', 'description']
    success_url = reverse_lazy('cookbook:ingredients')

    def get_context_data(self, **kwargs):
        """Return the context data

        :**kwargs: arguments
        :returns: context object for view

        """
        context = super(IngredientUpdate, self).get_context_data(**kwargs)
        context['version'] = settings.VERSION
        return context


class IngredientDelete(generic.edit.DeleteView):
    model = Ingredient
    success_url = reverse_lazy('cookbook:ingredients')


class MeasurementView(generic.ListView):

    """Display measurement set"""

    template_name = "cookbook/measurements.html"

    def get_context_data(self, **kwargs):
        """Return the context data

        :**kwargs: arguments
        :returns: context object for view

        """
        context = super().get_context_data(**kwargs)
        context['version'] = settings.VERSION
        return context

    def get_queryset(self):
        """Return set of measurements.
        :returns: list of measurements

        """
        return Measurement.objects.all()



class MeasurementCreate(generic.edit.CreateView):

    """Create a measurement object."""
    model = Measurement
    fields = ['name', 'stub', 'description']
    success_url = reverse_lazy('cookbook:measurements')

    def get_context_data(self, **kwargs):
        """Return the context data

        :**kwargs: arguments
        :returns: context object for view

        """
        context = super().get_context_data(**kwargs)
        context['version'] = settings.VERSION
        return context



class MeasurementEdit(generic.edit.UpdateView):

    """Edit measurements"""
    model = Measurement
    fields = ['name', 'stub', 'description']
    success_url = reverse_lazy('cookbook:measurements')

    def get_context_data(self, **kwargs):
        """Return the context data

        :**kwargs: arguments
        :returns: context object for view

        """
        context = super().get_context_data(**kwargs)
        context['version'] = settings.VERSION
        return context



class MeasurementDelete(generic.edit.DeleteView):

    """Delete a measurement from list."""
    model = Measurement
    success_url = reverse_lazy('cookbook:measurements')

cookbook/templates/cookbook/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>{% block title %} {% endblock title %}</title> 
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css" media="screen" title="no title" charset="utf-8">
        <link rel="stylesheet" href="{% static 'css/sticky-footer.css' %}" type="text/css" media="screen" title="no title" charset="utf-8">
        <style type="text/css">
            body > .container {
                padding-top: 60px;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Cookbook</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'cookbook:index' %}">Home</a></li>
                <li><a href="{% url 'cookbook:ingredients' %}">Ingredients</a></li>
                <li><a href="{% url 'cookbook:measurements' %}">Measurements</a></li>
            </ul>
            </div><!--/.nav-collapse -->
        </div>
        </nav>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
        <footer class="footer">
            <div class="container">
                <p class="text-muted">Version: {{version}}</p>
            </div>
        </footer>
        <script src="{% static 'js/bootstrap.js' %}" type="text/javascript" charset="utf-8"></script>
    </body>
</html>

cookbook/templates/cookbook/index.html
{% extends "cookbook/base.html" %}

{% block content %}
<h1>Hello cookbook</h1>
{% endblock content %}

cookbook/templates/cookbook/ingredient_confirm_delete.html
{% extends "cookbook/base.html" %}
{% load bootstrap3 %}
{% block title %}
    Confirm Delete Ingredient
{% endblock title %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>  
    <input type="submit" value="Confirm" />
</form>
{% endblock content %}

cookbook/templates/cookbook/ingredient_form.html
{% extends "cookbook/base.html" %}
{% load bootstrap3 %}
{% block title %}
    Create/Edit Ingredient
{% endblock title %}

{% block content %}
{% bootstrap_messages %} 
<form action="{{ request.path }}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
     {% bootstrap_icon "star" %}    Submit
    </button>
    {% endbuttons %}
</form>
{% endblock content %}

cookbook/templates/cookbook/ingredients.html
{% extends "cookbook/base.html" %}
{% load bootstrap3 %}
{% block title %} Ingredients {% endblock title %}
{% block content %}
<a href="{% url 'cookbook:create_ingredient' %}">Create ingredient</a>
    
    {% if ingredient_list %}
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th colspan="2">

            </th>
        </tr>
        {% for ingredient in ingredient_list %}
        <tr>
            <td>{{ingredient.name}}</td>
            <td>{{ingredient.description}}</td>
            <td><a href="{% url 'cookbook:edit_ingredient' ingredient.id %}">Edit</a></td>
            <td><a href="{% url 'cookbook:delete_ingredient' ingredient.id %}">Delete</a></td>
        </tr>
       {% endfor %} 
    </table>
    
    {% else %}
    <p>No ingredients available.</p>
    {% endif %}
    
{% endblock content %}

cookbook/templates/cookbook/measurement_confirm_delete.html
{% extends "cookbook/base.html" %}
{% load bootstrap3 %}
{% block title %}
    Confirm Delete Measurement
{% endblock title %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>  
    <input type="submit" value="Confirm" />
</form>
{% endblock content %}

cookbook/templates/cookbook/measurement_form.html
{% extends "cookbook/base.html" %}
{% load bootstrap3 %}
{% block title %}
    Create/Edit Measurement
{% endblock title %}
{% block content %}
    {% bootstrap_messages %}
    <form action="{{request.path}}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
        {% endbuttons %}
    </form>
{% endblock content %}

cookbook/templates/cookbook/measurements.html
{% extends "cookbook/base.html" %}

{% load bootstrap3 %}
{% block title %} Measurements {% endblock title %}
{% block content %}
<a href="{% url 'cookbook:create_measurement' %}"> Create </a>
   {% if measurement_list %}
   <table class="table">
       <tr>
           <th>Name</th>
           <th>Description</th>
           <th colspan="2">

           </th>
       </tr>
       {% for measurement in measurement_list %}
       <tr>
           <td>{{measurement.name}}</td>
           <td>{{measurement.description}}</td>
           <td><a href="{% url 'cookbook:edit_measurement' measurement.id %}">Edit</a></td>
           <td><a href="{% url 'cookbook:delete_measurement' measurement.id %}">Delete</a></td>
       </tr>
       {% endfor %}
   </table>
   {% else %}
        <p>No measurements available.</p>
   {% endif %} 
{% endblock content %}